### ISSUE TITLE
Getting an zeromq Error in windows 2010

### ISSUE THREAD

**Issue by dasdipa** [scrapinghub/frontera#137]
Process Process-1:
Traceback (most recent call last):
  File "C:\Anaconda2\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Anaconda2\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\neuromac\Admin.py", line 438, in start_proxy
    backend.close()
UnboundLocalError: local variable 'backend' referenced before assignment
Admin going to start with cfg_file:  random_walk\random_walk.cfg
Traceback (most recent call last):
  File "..\Admin.py", line 461, in <module>
    admin = Admin_Agent(no+1,cfg_file)
  File "..\Admin.py", line 50, in __init__
    self._initialize_communication_links()
  File "..\Admin.py", line 75, in _initialize_communication_links
    self.socket_pull.bind("tcp://*:%s" % self.parser.getint("system","pull_port"))
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq\backend\cython\socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\socket.c:7535)
    raise ZMQError(errno)
zmq.error.ZMQError: Address in use

**Comment by sibiryakov** [comment]
I see no signs that this is connected with frontera @dasdipa, this traceback tells me nothing. Do you have any details on what are you doing?
