### ISSUE TITLE
producer.stop() called, but producer is not async

### ISSUE THREAD

**Issue by nautilus28** [scrapinghub/frontera#157]
Hi,

I am trying to run Frontera with Kafka as Message bus.

Ubuntu 16.04 LTS
Python 2.7.11
Frontera 0.5.1.1

I placed BACKEND = 'frontera.contrib.backends.remote.kafka.KafkaOverusedBackend' in my spider_settings.py

when running the command: `scrapy crawl general -L INFO -s FRONTERA_SETTINGS=frontier.spider_settings -s SEEDS_SOURCE=seeds.txt -s SPIDER_PARTITION_ID=0`

I got following errors:
1. WARNING: producer.stop() called, but producer is not async
2. Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 90, in crawl
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 74, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
AttributeError: 'FrontierManager' object has no attribute 'logger

would it consider being a bug or did I miss some configurations? Please let me know if you have any advice.

Thank you,
Canh

**Comment by sibiryakov** [comment]
Hi Canh,

KafkaOverusedBackend is obsolete and going to be removed in the next versions, also could be outdated. Please try MessageBus backend with MESSAGE_BUS set to Kafka. This is a preferred way of running Frontera with Kafka.

Отправлено с iPhone

**Comment by nautilus28** [comment]
Hi @sibiryakov,

Thanks for your update.

I followed your advice to use following setup:

worker_settings.py
`BACKEND = 'frontera.contrib.backends.hbase.HBaseBackend'`
`MESSAGE_BUS = 'frontera.contrib.messagebus.kafkabus.MessageBus'`

spider_settings.py
`BACKEND = 'frontera.contrib.backends.remote.messagebus.MessageBusBackend'`
`MESSAGE_BUS = 'frontera.contrib.messagebus.kafkabus.MessageBus'`

The error disappears, however, the spider does not read my SEEDS_SOURCE file as input. Do you have any idea why?

Thank you so much for your help.

Kind regards,

**Comment by sibiryakov** [comment]
@nautilus28 do you have strategy worker running? if so, please check it reads the seeds and generates update_score events in the scoring log.

**Comment by nautilus28** [comment]
@sibiryakov yes, I have strategy worker running via: `python -m frontera.worker.strategy --config frontier.worker_settings --partition-id 0 --strategy frontera.worker.strategies.bfs.CrawlingStrategy`

The kafka.consumer has connected and read messages from topic='frontier-done' until the worker hang at:
2016-06-20 07:36:31,969 DEBUG    kafka.consumer.simple got 101 messages:...<encoded data>
2016-06-20 07:36:31,974 DEBUG    hbase.states    cache size 0
2016-06-20 07:36:31,974 DEBUG    hbase.states    to fetch 98 from 98

I don't see any scoring log yet, do you have any idea why?

Thanks,

**Comment by sibiryakov** [comment]
SW cannot access HBase, that's why. It generates events to scoring log after it fetches states from storage.

In a separate issue I mentioned transport & protocol have to fit, did you checked it?

**Comment by nautilus28** [comment]
I started hbase master and thrift server by:
/usr/lib/hbase/hbase-0.98.20-hadoop2/bin/start-hbase.sh
/usr/lib/hbase/hbase-0.98.20-hadoop2/bin/hbase-daemon.sh start thrift -threadpool

and I checked happybase connection by following
In [1]: import happybase

In [2]: c = happybase.Connection('localhost')

In [3]: print c.tables()
['test']

in worker_settings.py
`HBASE_DROP_ALL_TABLES = False`
`HBASE_THRIFT_PORT = 9090`
`HBASE_THRIFT_HOST = 'localhost'`

I have read the link you mentioned. The default -threadpool mode uses the "buffered" transport and the protocol binary as default. It seems that I correctly configured it.

**Comment by nautilus28** [comment]
I have inspected my strategy worker and I found that it hang on `records = table.rows(keys, columns=['s:state'])`
https://github.com/scrapinghub/frontera/blob/189a4bcebdef81a976626f8eb51758204e69896d/frontera/contrib/backends/hbase.py#L293

do you have any idea why?

**Comment by sibiryakov** [comment]
I have no idea why exactly, but I think this is something connected with usage of old 0.98.x versions. Please check:

1. if tables are created? if not, try changing the code and use default ``table_prefix_separator`` at https://github.com/scrapinghub/frontera/blob/189a4bcebdef81a976626f8eb51758204e69896d/frontera/contrib/backends/hbase.py#L385
2. if yes, try checking if the same way you checked table creation above if get/put works.

A.

**Comment by nautilus28** [comment]
which is the most suitable hbase version to work with frontera?

**Comment by sibiryakov** [comment]
The recent ones: HBase 1.x.x

**Comment by nautilus28** [comment]
Latest happybase release was on Nov 25, 2014. HappyBase uses the Python Thrift library to connect to HBase using its Thrift gateway, HBase using its Thrift gateway, which is included in the standard HBase 0.9x releases. I doubt it still works properly with HBase 1.x.x. But I will check that.

Thank you Alexander

**Comment by nautilus28** [comment]
I just played with hbase 1.1.5 by this guide: http://hbase.apache.org/book.html#quickstart
create table, put keys, scan keys, they all work fine with my setup.

But when I run the strategy worker, I got following error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/frontera/worker/db.py", line 277, in <module>
    worker = DBWorker(settings, args.no_batches, args.no_incoming)
  File "/usr/local/lib/python2.7/dist-packages/frontera/worker/db.py", line 71, in __init__
    self._manager = FrontierManager.from_settings(settings, db_worker=True)
  File "/usr/local/lib/python2.7/dist-packages/frontera/core/manager.py", line 282, in from_settings
    strategy_worker=strategy_worker)
  File "/usr/local/lib/python2.7/dist-packages/frontera/core/manager.py", line 243, in __init__
    strategy_worker=strategy_worker)
  File "/usr/local/lib/python2.7/dist-packages/frontera/core/manager.py", line 24, in __init__
    self._backend = self._load_backend(backend, db_worker, strategy_worker)
  File "/usr/local/lib/python2.7/dist-packages/frontera/core/manager.py", line 54, in _load_backend
    return cls.db_worker(self)
  File "/usr/local/lib/python2.7/dist-packages/frontera/contrib/backends/hbase.py", line 411, in db_worker
    settings.get('HBASE_QUEUE_TABLE'), drop=drop_all_tables)
  File "/usr/local/lib/python2.7/dist-packages/frontera/contrib/backends/hbase.py", line 76, in __init__
    self.connection.create_table(self.table_name, {'f': {'max_versions': 1, 'block_cache_enabled': 1}})
  File "/usr/local/lib/python2.7/dist-packages/happybase/connection.py", line 305, in create_table
    self.client.createTable(name, column_descriptors)
  File "/usr/local/lib/python2.7/dist-packages/happybase/hbase/Hbase.py", line 931, in createTable
    self.recv_createTable()
  File "/usr/local/lib/python2.7/dist-packages/happybase/hbase/Hbase.py", line 953, in recv_createTable
    raise result.io
happybase.hbase.ttypes.IOError: IOError(_message='org.apache.hadoop.hbase.NamespaceNotFoundException: org.apache.hadoop.hbase.NamespaceNotFoundException: crawler\n\tat org.apache.hadoop.hbase.master.HMaster.ensureNamespaceExists...

I think that happybase does not work with with hbase 1.1.5

**Comment by nautilus28** [comment]
I don’t get the framework running, does it really work yet? I am trying to implement this to a client, I have to try another framework if I don’t get this running. Is there a source code example of frontera crawler with hbase/kafka that I can look at?

**Comment by sibiryakov** [comment]
@nautilus28 in your previous message the error is quite clear - you have to create namespace. 

RTFM http://frontera.readthedocs.io/en/latest/topics/production-broad-crawling.html#production-broad-crawling

**Comment by casertap** [comment]
Hey @nautilus28 any news about your issue?
I am trying to make this work as well and I wouldn't mind some help if you succeeded to make it work in the past. 
My issue is here: https://github.com/scrapinghub/frontera/issues/198
I created a git repo with instruction on how to run it with docker 
https://github.com/casertap/frontera-google-docker

Note that I am using a command to create the namespace. That was the problem you had before.
