### ISSUE TITLE
exceptions.AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by nautilus28** [scrapinghub/frontera#159]
BACKEND = 'frontera.contrib.backends.hbase.HBaseBackend'
MESSAGE_BUS = 'frontera.contrib.messagebus.kafkabus.MessageBus'

It seems that there is a bug when not specifying SCORING_TOPIC

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/frontera/worker/strategy.py", line 260, in <module>
    worker.run()
  File "/usr/local/lib/python2.7/dist-packages/frontera/worker/strategy.py", line 191, in run
    self.task.start(interval=0)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 194, in start
    self()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/frontera/worker/strategy.py", line 175, in work
    self.update_score.flush()
  File "/usr/local/lib/python2.7/dist-packages/frontera/worker/strategy.py", line 41, in flush
    self._producer.send(None, *self._buffer)
  File "/usr/local/lib/python2.7/dist-packages/frontera/contrib/messagebus/kafkabus.py", line 81, in send
    self._producer.send_messages(self._topic, *messages)
  File "/usr/local/lib/python2.7/dist-packages/kafka/producer/simple.py", line 50, in send_messages
    topic = topic.encode('utf-8')
exceptions.AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by sibiryakov** [comment]
Hi Canh,

It's not a bug, HBaseBackend implies distributed backend and spiders run mode, therefore it requires strategy worker and scoring log set up.

Отправлено с iPhone

**Comment by nautilus28** [comment]
Is there any reason to not have a default value for SCORING_TOPIC?

**Comment by sibiryakov** [comment]
@nautilus28 this is going to be added with upcoming kafka-python 1.x.x support release.
