### ISSUE TITLE
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes

### ISSUE THREAD

**Issue by nautilus28** [scrapinghub/frontera#160]
Hi,

I am trying to run Frontera with Kafka as Message bus and Hbase as Backend.

Ubuntu 16.04 LTS
Python 2.7.11
Frontera 0.5.1.1
happybase 0.9.5
hbase-0.98.20-hadoop2
kafka 0.9.0.0
kafka-python 0.9.5

in worker_settings.py
`BACKEND = 'frontera.contrib.backends.hbase.HBaseBackend'`
`MESSAGE_BUS = 'frontera.contrib.messagebus.kafkabus.MessageBus'`

when I run start strategy worker, I got following error:
`python -m frontera.worker.strategy --config frontera.worker_settings --partition-id 0 --strategy frontera.worker.strategies.bfs.CrawlingStrategy`

Unhandled error in Deferred:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/frontera/worker/strategy.py", line 149, in work
    self.states_context.fetch()
  File "/usr/local/lib/python2.7/dist-packages/frontera/worker/strategy.py", line 60, in fetch
    self._states.fetch(self._fingerprints)
  File "/usr/local/lib/python2.7/dist-packages/frontera/contrib/backends/hbase.py", line 293, in fetch
    records = table.rows(keys, columns=['s:state'])
  File "/usr/local/lib/python2.7/dist-packages/happybase/table.py", line 155, in rows
    self.name, rows, columns, {})
  File "/usr/local/lib/python2.7/dist-packages/happybase/hbase/Hbase.py", line 1358, in getRowsWithColumns
    return self.recv_getRowsWithColumns()
  File "/usr/local/lib/python2.7/dist-packages/happybase/hbase/Hbase.py", line 1372, in recv_getRowsWithColumns
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
  File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TBinaryProtocol.py", line 126, in readMessageBegin
    sz = self.readI32()
  File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TBinaryProtocol.py", line 206, in readI32
    buff = self.trans.readAll(4)
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 58, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 159, in read
    self.__rbuf = StringIO(self.__trans.read(max(sz, self.__rbuf_size)))
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 120, in read
    message='TSocket read 0 bytes')
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes

Is this a bug or hbase configuration was not correctly setup? Please let me know if you have any idea.

Thanks in advanced,
Canh

**Comment by sibiryakov** [comment]
@nautilus28 it's probably connected with your Thrift client-server configuration. You should make sure your _transport_ and _protocol_ on the client (frontera workers) fit those on the server.

See also https://happybase.readthedocs.io/en/stable/api.html#happybase.Connection

**Comment by sibiryakov** [comment]
duplicates https://github.com/scrapinghub/frontera/issues/157#issuecomment-227425646
