### ISSUE TITLE
I can't run any script?

### ISSUE THREAD

**Issue by Bundas** [scrapinghub/frontera#170]
Hi, i get this error every time:
```python
2016-07-08 02:11:50 [boto] DEBUG: Retrieving credentials from metadata server.
2016-07-08 02:11:51 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/boto/utils.py", line 211, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
2016-07-08 02:11:51 [boto] ERROR: Unable to read instance data, giving up
```

This is full log:
```python
/home/jan/Documents/frontera/examples/scrapy_recording/scrapy_recording/spiders/recorder.py:29: ScrapyDeprecationWarning: SgmlLinkExtractor is deprecated and will be removed in future releases. Please use scrapy.linkextractors.LinkExtractor
  RegexLinkExtractor(allow=ALLOWED_RE),
2016-07-08 02:11:49 [scrapy] INFO: Scrapy 1.0.3 started (bot: scrapy_frontier)
2016-07-08 02:11:49 [scrapy] INFO: Optional features available: ssl, http11, boto
2016-07-08 02:11:49 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'scrapy_recording.spiders', 'CONCURRENT_REQUESTS_PER_DOMAIN': 2, 'CONCURRENT_REQUESTS': 256, 'RETRY_ENABLED': False, 'SPIDER_MODULES': ['scrapy_recording.spiders'], 'HTTPCACHE_ENABLED': True, 'BOT_NAME': 'scrapy_frontier', 'DOWNLOAD_TIMEOUT': 20, 'COOKIES_ENABLED': False, 'SCHEDULER': 'frontera.contrib.scrapy.schedulers.recording.RecorderScheduler', 'LOGSTATS_INTERVAL': 10}
2016-07-08 02:11:49 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState
2016-07-08 02:11:49 [py.warnings] WARNING: /usr/local/lib/python2.7/dist-packages/frontera/contrib/scrapy/schedulers/recording.py:5: ScrapyDeprecationWarning: Module `scrapy.log` has been deprecated, Scrapy now relies on the builtin Python library for logging. Read the updated logging entry in the documentation to learn more.
  from scrapy import log

2016-07-08 02:11:50 [boto] DEBUG: Retrieving credentials from metadata server.
2016-07-08 02:11:51 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/boto/utils.py", line 211, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
2016-07-08 02:11:51 [boto] ERROR: Unable to read instance data, giving up
2016-07-08 02:11:51 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, ChunkedTransferMiddleware, DownloaderStats, HttpCacheMiddleware, SchedulerDownloaderMiddleware
2016-07-08 02:11:51 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware, SchedulerSpiderMiddleware
2016-07-08 02:11:51 [scrapy] INFO: Enabled item pipelines: 
2016-07-08 02:11:51 [scrapy] INFO: Spider opened
2016-07-08 02:11:51 [py.warnings] WARNING: /usr/local/lib/python2.7/dist-packages/frontera/contrib/scrapy/schedulers/recording.py:65: ScrapyDeprecationWarning: log.msg has been deprecated, create a python logger and log through it instead
  log.msg('Starting recorder', log.INFO)

2016-07-08 02:11:51 [scrapy] INFO: Starting recorder
2016-07-08 02:11:51 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2016-07-08 02:11:51 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6024
2016-07-08 02:11:51 [scrapy] DEBUG: Redirecting (302) to <GET https://diffeo.com/> from <GET http://diffeo.com>
2016-07-08 02:11:51 [scrapy] DEBUG: Crawled (200) <GET https://diffeo.com/> (referer: None) ['cached']
2016-07-08 02:11:51 [scrapy] INFO: Closing spider (finished)
2016-07-08 02:11:51 [py.warnings] WARNING: /usr/local/lib/python2.7/dist-packages/frontera/contrib/scrapy/schedulers/recording.py:83: ScrapyDeprecationWarning: log.msg has been deprecated, create a python logger and log through it instead
  log.msg('Finishing recorder (%s)' % reason, log.INFO)

2016-07-08 02:11:51 [scrapy] INFO: Finishing recorder (finished
```
I tested on `examples/scrapy_recording` and `examples/general-spider`.
I have started db-worker but I don't think that this could be the problem.

Any idea? Btw. I think frontera is a bit buggy. I had to fix some frontera code in graph manager importing.

**Comment by sibiryakov** [comment]
Hi @Bundas, it looks like your code is somehow interacts with ``boto``. You didn't posted your configs, so I can't say where the problem is exactly, but I can assume you're trying to read seeds from s3 bucket and URL isn't accessible. So recommendation is to check my assumption, if it's wrong then post your Scrapy and Frontera settings files. 

``graph manager`` and ``scrapy_recording`` are quite untouched components for a long time, so it's probable there are some problems, please don't hesitate to submit PRs if you think your patches worth merging.

**Comment by sibiryakov** [comment]
can we close that @Bundas ?
