### ISSUE TITLE
ImportError: No module named 'core'

### ISSUE THREAD

**Issue by lwm** [scrapinghub/frontera#172]
```
(.venv) [cortex][integrate-frontera] ⚡ λ pip freeze | grep frontera                                                                                                   [node-5.5.0][ruby-2.2.1]
frontera==0.5.2.2

(.venv) [cortex][integrate-frontera] ⚡ λ pip --version                                                                                                                [node-5.5.0][ruby-2.2.1]
pip 8.1.2 from /home/lwm/work/contrib/cortex/.venv/lib/python3.5/site-packages (python 3.5)

(.venv) [cortex][integrate-frontera] ⚡ λ python                                                                                                                       [node-5.5.0][ruby-2.2.1]
Python 3.5.1 (default, Dec 18 2015, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import frontera
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lwm/work/contrib/cortex/.venv/lib/python3.5/site-packages/frontera/__init__.py", line 1, in <module>
    from core.manager import FrontierManager
ImportError: No module named 'core'
```

**Comment by redapple** [comment]
hi @lwm , please note that Frontera is not yet Python3-compatible

**Comment by lwm** [comment]
@redapple Thanks for the heads up (just found https://github.com/scrapinghub/frontera/issues/106)

You think it is related? I tried on python 2.7.6 and got #173.

**Comment by sibiryakov** [comment]
can we close that for now @lwm ?

**Comment by lwm** [comment]
Sure, fire away. I will keep an eye on #106.

**Comment by sibiryakov** [comment]
Hey @lwm we have Python 3 support released, please have a look! https://github.com/scrapinghub/frontera/releases/tag/v0.6.0
