### ISSUE TITLE
Strategy worker error

### ISSUE THREAD

**Issue by kazuar** [scrapinghub/frontera#266]
Hello,

I have frontera setup with Kafka and Hbase.
Every once in a while I get the following errors in the strategy worker (BCPerHostLimit):

```
[strategy-worker] last_consumed=0
INFO:strategy-worker:last_consumed=0
[strategy-worker] consumed_since_start=6313
INFO:strategy-worker:consumed_since_start=6313
[strategy-worker] last_consumption_run=Thu Mar  9 18:40:10 2017
INFO:strategy-worker:last_consumption_run=Thu Mar  9 18:40:10 2017
[strategy-worker] Flushing states
INFO:strategy-worker:Flushing states
[strategy-worker] [Errno 32] Broken pipe
None
ERROR:strategy-worker:[Errno 32] Broken pipe
None
[strategy-worker]   File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/frontera/worker/strategy.py", line 247, in flush_states
    self.states_context.flush()
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/frontera/worker/strategy.py", line 78, in flush
    self._states.flush(force_clear=False)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/frontera/contrib/backends/hbase.py", line 303, in flush
    b.put(unhexlify(fprint), hb_obj)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/happybase/batch.py", line 137, in __exit__
    self.send()
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/happybase/batch.py", line 60, in send
    self._table.connection.client.mutateRows(self._table.name, bms, {})
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/thriftpy/thrift.py", line 195, in _req
    self._send(_api, **kwargs)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/thriftpy/thrift.py", line 205, in _send
    args.write(self._oprot)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/thriftpy/thrift.py", line 153, in write
    oprot.write_struct(self)
  File "thriftpy/protocol/cybin/cybin.pyx", line 477, in cybin.TCyBinaryProtocol.write_struct (thriftpy/protocol/cybin/cybin.c:7205)
  File "thriftpy/protocol/cybin/cybin.pyx", line 474, in cybin.TCyBinaryProtocol.write_struct (thriftpy/protocol/cybin/cybin.c:7127)
  File "thriftpy/protocol/cybin/cybin.pyx", line 212, in cybin.write_struct (thriftpy/protocol/cybin/cybin.c:3342)
  File "thriftpy/protocol/cybin/cybin.pyx", line 356, in cybin.c_write_val (thriftpy/protocol/cybin/cybin.c:5142)
  File "thriftpy/protocol/cybin/cybin.pyx", line 115, in cybin.write_list (thriftpy/protocol/cybin/cybin.c:2115)
  File "thriftpy/protocol/cybin/cybin.pyx", line 362, in cybin.c_write_val (thriftpy/protocol/cybin/cybin.c:5200)
  File "thriftpy/protocol/cybin/cybin.pyx", line 212, in cybin.write_struct (thriftpy/protocol/cybin/cybin.c:3342)
  File "thriftpy/protocol/cybin/cybin.pyx", line 353, in cybin.c_write_val (thriftpy/protocol/cybin/cybin.c:5112)
  File "thriftpy/protocol/cybin/cybin.pyx", line 122, in cybin.write_string (thriftpy/protocol/cybin/cybin.c:2202)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 55, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_write (thriftpy/transport/buffered/cybuffered.c:1753)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 80, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_flush (thriftpy/transport/buffered/cybuffered.c:2147)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/thriftpy/transport/socket.py", line 129, in write
    self.sock.sendall(buff)
  File "/home/ubuntu/miniconda2/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)

CRITICAL:strategy-worker:  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/frontera/worker/strategy.py", line 247, in flush_states
    self.states_context.flush()
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/frontera/worker/strategy.py", line 78, in flush
    self._states.flush(force_clear=False)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/frontera/contrib/backends/hbase.py", line 303, in flush
    b.put(unhexlify(fprint), hb_obj)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/happybase/batch.py", line 137, in __exit__
    self.send()
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/happybase/batch.py", line 60, in send
    self._table.connection.client.mutateRows(self._table.name, bms, {})
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/thriftpy/thrift.py", line 195, in _req
    self._send(_api, **kwargs)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/thriftpy/thrift.py", line 205, in _send
    args.write(self._oprot)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/thriftpy/thrift.py", line 153, in write
    oprot.write_struct(self)
  File "thriftpy/protocol/cybin/cybin.pyx", line 477, in cybin.TCyBinaryProtocol.write_struct (thriftpy/protocol/cybin/cybin.c:7205)
  File "thriftpy/protocol/cybin/cybin.pyx", line 474, in cybin.TCyBinaryProtocol.write_struct (thriftpy/protocol/cybin/cybin.c:7127)
  File "thriftpy/protocol/cybin/cybin.pyx", line 212, in cybin.write_struct (thriftpy/protocol/cybin/cybin.c:3342)
  File "thriftpy/protocol/cybin/cybin.pyx", line 356, in cybin.c_write_val (thriftpy/protocol/cybin/cybin.c:5142)
  File "thriftpy/protocol/cybin/cybin.pyx", line 115, in cybin.write_list (thriftpy/protocol/cybin/cybin.c:2115)
  File "thriftpy/protocol/cybin/cybin.pyx", line 362, in cybin.c_write_val (thriftpy/protocol/cybin/cybin.c:5200)
  File "thriftpy/protocol/cybin/cybin.pyx", line 212, in cybin.write_struct (thriftpy/protocol/cybin/cybin.c:3342)
  File "thriftpy/protocol/cybin/cybin.pyx", line 353, in cybin.c_write_val (thriftpy/protocol/cybin/cybin.c:5112)
  File "thriftpy/protocol/cybin/cybin.pyx", line 122, in cybin.write_string (thriftpy/protocol/cybin/cybin.c:2202)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 55, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_write (thriftpy/transport/buffered/cybuffered.c:1753)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 80, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_flush (thriftpy/transport/buffered/cybuffered.c:2147)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/thriftpy/transport/socket.py", line 129, in write
    self.sock.sendall(buff)
  File "/home/ubuntu/miniconda2/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)

[strategy-worker] Flushing states
INFO:strategy-worker:Flushing states
[strategy-worker] [Errno 32] Broken pipe
None
ERROR:strategy-worker:[Errno 32] Broken pipe
None
```

And when I close the strategy worker, I get the following error:

```
Unhandled Error
Traceback (most recent call last):
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/twisted/internet/base.py", line 1199, in run
    self.mainLoop()
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/twisted/internet/base.py", line 1208, in mainLoop
    self.runUntilCurrent()
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/twisted/internet/base.py", line 850, in runUntilCurrent
    self.fireSystemEvent("shutdown")
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/twisted/internet/base.py", line 643, in fireSystemEvent
    event.fireEvent()
--- <exception caught here> ---
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/twisted/internet/base.py", line 414, in fireEvent
    result = callable(*args, **kwargs)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/frontera/worker/strategy.py", line 251, in stop
    self.strategy.close()
  File "general_scraper/broadcrawl/__init__.py", line 117, in close
    self.domain_cache.flush()
  File "general_scraper/broadcrawl/__init__.py", line 46, in flush
    self._store_item(b, k, v)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/happybase/batch.py", line 137, in __exit__
    self.send()
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/happybase/batch.py", line 60, in send
    self._table.connection.client.mutateRows(self._table.name, bms, {})
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/thriftpy/thrift.py", line 195, in _req
    self._send(_api, **kwargs)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/thriftpy/thrift.py", line 205, in _send
    args.write(self._oprot)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/thriftpy/thrift.py", line 153, in write
    oprot.write_struct(self)
  File "thriftpy/protocol/cybin/cybin.pyx", line 477, in cybin.TCyBinaryProtocol.write_struct (thriftpy/protocol/cybin/cybin.c:7205)

  File "thriftpy/protocol/cybin/cybin.pyx", line 474, in cybin.TCyBinaryProtocol.write_struct (thriftpy/protocol/cybin/cybin.c:7127)

  File "thriftpy/protocol/cybin/cybin.pyx", line 212, in cybin.write_struct (thriftpy/protocol/cybin/cybin.c:3342)

  File "thriftpy/protocol/cybin/cybin.pyx", line 356, in cybin.c_write_val (thriftpy/protocol/cybin/cybin.c:5142)

  File "thriftpy/protocol/cybin/cybin.pyx", line 115, in cybin.write_list (thriftpy/protocol/cybin/cybin.c:2115)

  File "thriftpy/protocol/cybin/cybin.pyx", line 362, in cybin.c_write_val (thriftpy/protocol/cybin/cybin.c:5200)

  File "thriftpy/protocol/cybin/cybin.pyx", line 212, in cybin.write_struct (thriftpy/protocol/cybin/cybin.c:3342)

  File "thriftpy/protocol/cybin/cybin.pyx", line 356, in cybin.c_write_val (thriftpy/protocol/cybin/cybin.c:5142)

  File "thriftpy/protocol/cybin/cybin.pyx", line 115, in cybin.write_list (thriftpy/protocol/cybin/cybin.c:2115)

  File "thriftpy/protocol/cybin/cybin.pyx", line 362, in cybin.c_write_val (thriftpy/protocol/cybin/cybin.c:5200)

  File "thriftpy/protocol/cybin/cybin.pyx", line 212, in cybin.write_struct (thriftpy/protocol/cybin/cybin.c:3342)

  File "thriftpy/protocol/cybin/cybin.pyx", line 353, in cybin.c_write_val (thriftpy/protocol/cybin/cybin.c:5112)

  File "thriftpy/protocol/cybin/cybin.pyx", line 122, in cybin.write_string (thriftpy/protocol/cybin/cybin.c:2202)

  File "thriftpy/transport/buffered/cybuffered.pyx", line 55, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_write (thriftpy/transport/buffered/cybuffered.c:1753)

  File "thriftpy/transport/buffered/cybuffered.pyx", line 80, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_flush (thriftpy/transport/buffered/cybuffered.c:2147)

  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/thriftpy/transport/socket.py", line 129, in write
    self.sock.sendall(buff)
  File "/home/ubuntu/miniconda2/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 32] Broken pipe

INFO:kafka.producer.kafka:Closing the Kafka producer with 999999999 secs timeout.
```

I'm trying to understand what the actual error is, where it's coming from and how to debug this.

A few notes:
1) I'm running Hbase, Kafka and Frontera on a single machine (ubuntu).
2) The implemented SW (strategy worker) is [BCPerHostLimit](https://github.com/scrapinghub/frontera/blob/master/examples/cluster/bc/broadcrawl/__init__.py#L48)
2) It seems to be happening at random times but once it starts it will keep throwing errors until there's nothing left to crawl.
3) There aren't seem to be errors or warnings in the db worker, crawler, kafka logs or hbase thrift logs.
4) I run the SW (strategy worker) with the following command:
```
python -m frontera.worker.strategy --config general_scraper.config.sw --partition-id 0
```

Any advice or help on how to approach this would be much appreciated.
Thanks!

**Comment by sibiryakov** [comment]
This is definitely related to your connection of SW to Thrift. I'm suggesting to evaluate settings for Thrift server closely and also look at it's load. IMO, it closes connection prematurely because of some error. Another approach is to try switching to framed transport (meaning nonblocking server) and compact protocol.

**Comment by kazuar** [comment]
@sibiryakov Thanks for the help!

I wanted to know if perhaps you could point me to what configuration I should use.
I've installed 2 environments on OSX and Ubuntu.
On both of these environments I'm getting the same "broken pipe" errors that I posted above.
Sometimes I get the error from the strategy worker and sometimes from the database worker.

I'm running thrift with the following command:
```
hbase thrift start -threadpool
```

Perhaps, if possible, you know of a working thrift configuration as I'm not sure if the problem is in Hbase or hadoop?

**Comment by colmex** [comment]
@kazuar were you able to resolve this issue? having the same issue now

**Comment by kazuar** [comment]
@colmex sorry, but I wasn't able to solve this issue. I got these errors from different workers at random times which made it very difficult to find the actual problem. I thought that maybe it was an environment configuration but I expected the errors to be more consistent if it was a configuration problem. I ended up using a different framework. Let me know if I can help with anything as I wanted this to work but I couldn't get around these errors.

**Comment by colmex** [comment]
@kazuar hmmm okay, thanks!
I was able to reproduce the error so I'm gonna try to debug the thrift issues. I have it working in docker with docker-compose, but I'm trying to migrate it over to kubernetes for production, sadly this issue is coming up and I'm guessing it's something within kubernetes messing up the thrift server. If you're interested (or for posterity) here's how I can reproduce the error:
- go into one of the strategy worker containers (e.g. `kubectl exec -it {{ pod name }} /bin/bash`
- open a python shell by running `python`
- run the following in the shell
```
import happybase
connection = happybase.Connection('hbase')
table = connection.table('crawler:queue')
for i in table.scan():
    print(i)
```
This will cause it fail in the same way that the strategy worker fails. So it's clearly something with the thrift server going wrong.

**Comment by colmex** [comment]
@kazuar sidenote what other framework did you end up using?

**Comment by kazuar** [comment]
@colmex thanks! This is interesting because I did try to isolate the issue (though it's been a while so I don't remember exactly what I did). I'll try to find the instance and run this again. 

I ended up using [scrapy-cluster](https://github.com/istresearch/scrapy-cluster) which is scrapy running with a scheduler that uses redis and kafka.

[This is a list of different distributed scrapy projects](http://scrapy-cluster.readthedocs.io/en/latest/topics/advanced/comparison.html)

If you happen to find the cause of the issue please post it here 😄

**Comment by colmex** [comment]
@kazuar 
Figured it out! I ended up having to pin the version of hbase at 0.98. So I'm using https://hub.docker.com/r/harisekhon/hbase/tags/ with the `0.98` tag.

**Comment by sibiryakov** [comment]
Luiz,

It's quite likely connected with the thrift server protocol and transport type. Try it with non-blocking transport and compact protocol.

When you start server use the options:
-compact and
-non-blocking

All that is true only if HBASE_USE_FRAMED_COMPACT is set to True, if not it uses the usual binary protocol and threaded transport. If your options on the client and server fit, check your connection to the port, perhaps it's not connecting or blocked or whatever.

A.
