### ISSUE TITLE
KeyError: b'frontier_request'

### ISSUE THREAD

**Issue by nmweizi** [scrapinghub/frontera#337]
- python3.6 
- centos7
- Scrapy 1.5.1
- frontera 0.8.0
- scrapy crawl zztj

2018-07-28 16:32:46 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: nmgkInfoCrawl)
2018-07-28 16:32:46 [scrapy.utils.log] INFO: Versions: lxml 4.2.3.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.3 (default, Jan  4 2018, 16:40:53) - [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.3, Platform Linux-3.10.0-693.el7.x86_64-x86_64-with-centos-7.4.1708-Core
2018-07-28 16:32:46 [scrapy.crawler] INFO: Overridden settings: {'AJAXCRAWL_ENABLED': True, 'BOT_NAME': 'nmgkInfoCrawl', 'CONCURRENT_REQUESTS': 64, 'COOKIES_ENABLED': False, 'HTTPCACHE_IGNORE_HTTP_CODES': [403], 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'nmgkInfoCrawl.spiders', 'RETRY_TIMES': 5, 'SCHEDULER': 'frontera.contrib.scrapy.schedulers.frontier.FronteraScheduler', 'SPIDER_MODULES': ['nmgkInfoCrawl.spiders']}
2018-07-28 16:32:46 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
2018-07-28 16:32:46 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.ajaxcrawl.AjaxCrawlMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats',
 'frontera.contrib.scrapy.middlewares.schedulers.SchedulerDownloaderMiddleware']
2018-07-28 16:32:46 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware',
 'frontera.contrib.scrapy.middlewares.schedulers.SchedulerSpiderMiddleware']
2018-07-28 16:32:46 [scrapy.middleware] INFO: Enabled item pipelines:
['nmgkInfoCrawl.save_sqlite.scrapyPipeline_sqlite']
2018-07-28 16:32:46 [scrapy.core.engine] INFO: Spider opened
2018-07-28 16:32:46 [manager] INFO: --------------------------------------------------------------------------------
2018-07-28 16:32:46 [manager] INFO: Starting Frontier Manager...
2018-07-28 16:32:46 [manager] INFO: Frontier Manager Started!
2018-07-28 16:32:46 [manager] INFO: --------------------------------------------------------------------------------
2018-07-28 16:32:46 [frontera.contrib.scrapy.schedulers.FronteraScheduler] INFO: Starting frontier
2018-07-28 16:32:46 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-07-28 1

2018-07-28 16:12:14 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.nm.zsks.cn/18gkwb/index_5.html> (referer: None)
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/usr/local/lib64/python3.6/site-packages/scrapy/spidermiddlewares/offsite.py", line 30, in process_spider_output
    for x in result:
  File "/usr/local/lib64/python3.6/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/local/lib64/python3.6/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib64/python3.6/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python3.6/site-packages/frontera/contrib/scrapy/schedulers/frontier.py", line 112, in process_spider_output
    frontier_request = response.meta[b'frontier_request']
KeyError: b'frontier_request'

**Comment by nmweizi** [comment]
@sibiryakov is fine.thx.

**Comment by liho00** [comment]
@nmweizi  hi, i have the same issue, could you please tell me how to solve?
```
2019-07-04 13:34:20 [scrapy.core.scraper] ERROR: Spider error processing <GET https://app.theculturetrip.com/cultureTrip-api/v2/articles?kgID=13211594601088724956&queryType=location_page&offset=0&limit=15> (referer: None)
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/opt/anaconda3/lib/python3.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/opt/anaconda3/lib/python3.7/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/opt/anaconda3/lib/python3.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/opt/anaconda3/lib/python3.7/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/opt/anaconda3/lib/python3.7/site-packages/frontera/contrib/scrapy/schedulers/frontier.py", line 112, in process_spider_output
    frontier_request = response.meta[b'frontier_request']
KeyError: b'frontier_request'
2019-07-04 13:35:19 [scrapy.extensions.logstats] INFO: Crawled 2 pages (at 2 pages/min), scraped 0 items (at 0 items/min)
2019-07-04 13:36:19 [scrapy.extensions.logstats] INFO: Crawled 2 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
```
@sibiryakov 
spider.py
```
class TutorialSpider(scrapy.Spider):
    name = 'tutorial'
    allowed_domains = ["theculturetrip.com"]
    offset = 0
    start_urls = ['https://app.theculturetrip.com/cultureTrip-api/v2/articles?kgID=13211594601088724956&queryType=location_page&offset='+str(offset)+'&limit=15']
    scrolled_article = []
    header = {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'Origin': 'https://theculturetrip.com',
        'Referer': 'https://theculturetrip.com/asia/malaysia/',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36'
    }

    def __init__(self, *args, **kwargs):
        super(TutorialSpider, self).__init__(*args, **kwargs)
        self.le = LinkExtractor()

    def parse(self, response):
        print(response.text)
        print('debug')        
        self.offset = self.offset + 15
        next_url = response.urljoin('https://app.theculturetrip.com/cultureTrip-api/v2/articles?kgID=13211594601088724956&queryType=location_page&offset='+str(self.offset)+'&limit=15')
        r = Request(url=next_url)
        r.headers.update(self.header)
        yield r

    @classmethod
    def from_crawler(cls, crawler, *args, **kwargs):
        spider = cls(*args, **kwargs)
        spider._set_crawler(crawler)
        spider.crawler.signals.connect(
            spider.spider_idle, signal=signals.spider_idle)
        return spider

    def spider_idle(self):
        self.log("Spider idle signal caught.")
        raise exceptions.DontCloseSpider
```
crawling strategic is `BasicCrawlingStrategy`

My use case is follow the website pagination to crawl next page, all crawl the item details.
