### ISSUE TITLE
NameError: Module 'frontera.contrib.backends.sqlalchemy' doesn't define any object named 'SQLAlchemyBackend'

### ISSUE THREAD

**Issue by nmweizi** [scrapinghub/frontera#339]
- python3.6
- centos7
- Scrapy 1.5.1
- frontera 0.8.0
- run general-spider
- Second, let’s start DB worker.
- python36 -m frontera.worker.db --config frontier.workersettings
 2018-07-28 17:02:01,680 INFO     manager         --------------------------------------------------------------------------------
 2018-07-28 17:02:01,680 INFO     manager         Starting Frontier Manager...
 2018-07-28 17:02:01,680 DEBUG    manager.components Loading canonical url solver 'None'
 2018-07-28 17:02:01,680 DEBUG    manager.components Loading backend 'frontera.contrib.backends.sqlalchemy.SQLAlchemyBackend'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/frontera-0.8.0.post0.dev1-py3.6.egg/frontera/utils/misc.py", line 41, in load_object
    obj = getattr(mod, name)
AttributeError: module 'frontera.contrib.backends.sqlalchemy' has no attribute 'SQLAlchemyBackend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/frontera-0.8.0.post0.dev1-py3.6.egg/frontera/worker/db.py", line 246, in <module>
    args.no_scoring, partitions=args.partitions)
  File "/usr/lib/python3.6/site-packages/frontera-0.8.0.post0.dev1-py3.6.egg/frontera/worker/stats.py", line 22, in __init__
    super(StatsExportMixin, self).__init__(settings, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/frontera-0.8.0.post0.dev1-py3.6.egg/frontera/worker/db.py", line 102, in __init__
    self._manager = WorkerFrontierManager.from_settings(settings, db_worker=True)
  File "/usr/lib/python3.6/site-packages/frontera-0.8.0.post0.dev1-py3.6.egg/frontera/core/manager.py", line 691, in from_settings
    return WorkerFrontierManager(**kwargs)
  File "/usr/lib/python3.6/site-packages/frontera-0.8.0.post0.dev1-py3.6.egg/frontera/core/manager.py", line 665, in __init__
    ComponentsPipelineMixin.__init__(self, backend, db_worker=db_worker, strategy_worker=strategy_worker)
  File "/usr/lib/python3.6/site-packages/frontera-0.8.0.post0.dev1-py3.6.egg/frontera/core/manager.py", line 87, in __init__
    BackendMixin.__init__(self, backend, db_worker, strategy_worker)
  File "/usr/lib/python3.6/site-packages/frontera-0.8.0.post0.dev1-py3.6.egg/frontera/core/manager.py", line 20, in __init__
    self._backend = self._load_backend(backend, db_worker, strategy_worker)
  File "/usr/lib/python3.6/site-packages/frontera-0.8.0.post0.dev1-py3.6.egg/frontera/core/manager.py", line 25, in _load_backend
    cls = load_object(backend)
  File "/usr/lib/python3.6/site-packages/frontera-0.8.0.post0.dev1-py3.6.egg/frontera/utils/misc.py", line 43, in load_object
    raise NameError("Module '%s' doesn't define any object named '%s'" % (module, name))
NameError: Module 'frontera.contrib.backends.sqlalchemy' doesn't define any object named 'SQLAlchemyBackend'

**Comment by sibiryakov** [comment]
Hi @nmweizi, yep general-spider example is outdated.

**Comment by sibiryakov** [comment]
fixed in 0.8.0.1
