### ISSUE TITLE
Got error "ERROR:messagebus.stats:TClient instance has no attribute 'get_stats'"

### ISSUE THREAD

**Issue by kevin-ZZZ** [scrapinghub/frontera#359]
I'm new to frontera,when connect hbase,this error ouucred:

when I follow the frontera docs and run command “p[ython -m frontera.worker.db --config  config.dbw --no-incoming --partitions 0 1](https://frontera.readthedocs.io/en/latest/topics/cluster-setup.html)”  

ERROR:messagebus.stats:TClient instance has no attribute 'get_stats'
NoneType: None
CRITICAL:messagebus.stats:  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/frontera/worker/stats.py", line 75, in export_stats
    stats = self.get_stats()
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/frontera/worker/stats.py", line 95, in get_stats
    stats.update(self.backend.get_stats() or {})
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/frontera/contrib/backends/hbase/__init__.py", line 608, in get_stats
    stats.update(self.connection.client.get_stats())
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/thriftpy/thrift.py", line 184, in __getattr__
    self.__class__.__name__, _api))

I'm not sure how came this issue,and I got a lot of Error like this,finally the program off because of recursion. 
version of Hbase : 2.1.0
version of happyBase : 1.1.0
version of thriftpy : 0.3.9

Thanks for help!

**Comment by sibiryakov** [comment]
Hi @kevin-ZZZ thanks for reporting! This code is using our internal version of Happybase, and `get_stats()` method wasn't defined in public Happybase. You can fix that by removing this call, appreciate if you could submit a patch for this.

**Comment by kevin-ZZZ** [comment]
hi，@sibiryakov I'm not quite sure what you mean. 
   get_stats is for redefining/transforming stats data in child class; if just remove it violently,will it cause loss or error in feature(by the time I ask the question ,I did not finish reading all the code)？or  can you give me a declaration of get_stats() in your happybase.

**Comment by sibiryakov** [comment]
It shouldn't cause any errors, because the data returned by `get_stats()` is send directly to metrics stream/topic, and when absent, there shouldn't be any fails.

**Comment by sibiryakov** [comment]
https://github.com/scrapinghub/frontera/commit/dfdc396fbd3c73a0bbf7ebc169bf21ab3ce3e3c2

**Comment by sibiryakov** [comment]
let me know, if there is anything else.

**Comment by kevin-ZZZ** [comment]
@sibiryakov ,Thanks for the help.

command:
    (frontrea) kevin@ubuntu:~/project/freeProxy$ scrapy crawl kuaidaili -L INFO -s SPIDER_PARTITION_ID=1

Unhandled error in Deferred:
2019-01-16 20:20:49 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/crawler.py", line 171, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/crawler.py", line 175, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/core/scraper.py", line 69, in __init__
    self.spidermw = SpiderMiddlewareManager.from_crawler(crawler)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
    
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    
builtins.ModuleNotFoundError: No module named 'frontera.contrib.scrapy.middlewares.seeds'

2019-01-16 20:20:49 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/core/scraper.py", line 69, in __init__
    self.spidermw = SpiderMiddlewareManager.from_crawler(crawler)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
(frontrea) kevin@ubuntu:~/project/freeProxy$ 
(frontrea) kevin@ubuntu:~/project/freeProxy$ scrapy crawl kuaidaili -L INFO -s SPIDER_PARTITION_ID=1
/home/kevin/project/freeProxy/freeProxy/spiders/kuaidaili.py:2: ScrapyDeprecationWarning: Module `scrapy.spider` is deprecated, use `scrapy.spiders` instead
  from scrapy.spider import CrawlSpider, Rule
2019-01-16 20:21:23 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: freeProxy)
2019-01-16 20:21:23 [scrapy.utils.log] INFO: Versions: lxml 4.3.0.0, libxml2 2.9.9, cssselect 1.0.3, parsel 1.5.1, w3lib 1.19.0, Twisted 18.9.0, Python 3.6.7 (default, Oct 22 2018, 11:32:17) - [GCC 8.2.0], pyOpenSSL 18.0.0 (OpenSSL 1.1.0j  20 Nov 2018), cryptography 2.4.2, Platform Linux-4.15.0-29-generic-x86_64-with-Ubuntu-18.04-bionic
2019-01-16 20:21:23 [scrapy.crawler] INFO: Overridden settings: {'AUTOTHROTTLE_ENABLED': True, 'AUTOTHROTTLE_MAX_DELAY': 3.0, 'AUTOTHROTTLE_START_DELAY': 0.25, 'BOT_NAME': 'freeProxy', 'CONCURRENT_REQUESTS': 3, 'CONCURRENT_REQUESTS_PER_DOMAIN': 10, 'COOKIES_ENABLED': False, 'DNS_TIMEOUT': 180, 'DOWNLOAD_DELAY': 0.5, 'DOWNLOAD_MAXSIZE': 1048576, 'DOWNLOAD_TIMEOUT': 240, 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'freeProxy.spiders', 'RANDOMIZE_DOWNLOAD_DELAY': False, 'REACTOR_THREADPOOL_MAXSIZE': 32, 'RETRY_ENABLED': False, 'SCHEDULER': 'frontera.contrib.scrapy.schedulers.frontier.FronteraScheduler', 'SPIDER_MODULES': ['freeProxy.spiders']}
2019-01-16 20:21:23 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.throttle.AutoThrottle']
2019-01-16 20:21:23 [py.warnings] WARNING: /home/kevin/project/freeProxy/freeProxy/middlewares.py:11: ScrapyDeprecationWarning: Module `scrapy.log` has been deprecated, Scrapy now relies on the builtin Python library for logging. Read the updated logging entry in the documentation to learn more.
  from scrapy import log

2019-01-16 20:21:23 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'freeProxy.middlewares.RandomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats',
 'frontera.contrib.scrapy.middlewares.schedulers.SchedulerDownloaderMiddleware']
Unhandled error in Deferred:
2019-01-16 20:21:23 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/crawler.py", line 171, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/crawler.py", line 175, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/core/scraper.py", line 69, in __init__
    self.spidermw = SpiderMiddlewareManager.from_crawler(crawler)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
    
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    
builtins.ModuleNotFoundError: No module named 'frontera.contrib.scrapy.middlewares.seeds'

2019-01-16 20:21:23 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/core/scraper.py", line 69, in __init__
    self.spidermw = SpiderMiddlewareManager.from_crawler(crawler)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/site-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/home/kevin/.virtualenvs/frontrea/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'frontera.contrib.scrapy.middlewares.seeds'

A new problem occur, I believe i've inject seeds through command line,so I'm confused about the error here,Does it really need the module?

**Comment by sibiryakov** [comment]
no, this module is not needed. Since the latest version seeds have to be injected using strategy worker.

**Comment by liho00** [comment]
@sibiryakov how to inject the seeds using strategic worker?
